# Mozilla User Preferences
/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1361421312);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1366251402);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.keywordURLPromptDeclined", 1);
user_pref("browser.migration.version", 8);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.selectedEngine", "");
user_pref("browser.startup.homepage", "www.yahoo.com");
user_pref("browser.startup.homepage_override.buildID", "20130201065344");
user_pref("browser.startup.homepage_override.mstone", "18.0.2");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7Bb920380d-fbe7-45c7-96ab-37e9870a566c%7D:10.15.2.23,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1361421300153}}},{\"name\":\"app-profile\",\"addons\":{\"{b920380d-fbe7-45c7-96ab-37e9870a566c}\":{\"descriptor\":\"C:\\\\Users\\\\w7dev\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\4abbphxc.default\\\\extensions\\\\{b920380d-fbe7-45c7-96ab-37e9870a566c}\",\"mtime\":1366251135954}}}]");
user_pref("extensions.lastAppVersion", "18.0.2");
user_pref("extensions.lastPlatformVersion", "18.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130201065344");
user_pref("gecko.mstone", "18.0.2");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 53676);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1366251142);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1368036062);
user_pref("versionFromInstaller", "10.15.2.23");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");